name: Warehouse
channels:
  - defaults
dependencies:
  - python=3.8  # Specify your Python version
  - pip
  - Faker==8.19.0
  - pandas==1.3.3
  - seaborn==0.11.2
  - statsmodels==0.13.0
  - matplotlib==3.4.3
